# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hello Gensan
email: mail@hellogensan.com
description: > # this means to ignore newlines until "baseurl:"
  What's happening in General Santos City
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hellogensan.com" # the base hostname & protocol for your site
twitter_username: _hellogensan
github_username:

permalink: blog/:title/

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-sitemap
  - jemoji